"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { zodResolver } from "@hookform/resolvers/zod";
import { Download, Pencil, Plus, Route, ShieldAlert, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { PageHeader } from "@/components/common/page-header";
import { RiskBadge } from "@/components/common/risk-badge";
import { useAppStore } from "@/components/providers/app-store";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { REGIONS } from "@/config/regions";
import { downloadText } from "@/lib/utils";

const schema=z.object({regionCode:z.string().min(1,"행정동을 선택하세요."),note:z.string().max(100,"메모는 100자 이내로 입력하세요."),startDate:z.string().min(1,"시작일을 입력하세요."),endDate:z.string().min(1,"종료일을 입력하세요."),consent:z.boolean().refine(Boolean,"저장에 동의해야 합니다.")}).refine((value)=>value.startDate<=value.endDate,{message:"종료일은 시작일보다 빠를 수 없습니다.",path:["endDate"]});
type FormValues=z.infer<typeof schema>;

export function VisitManager(){const search=useSearchParams();const {visits,saveVisit,loadDemoRoute,deleteVisit,clearVisits,matches,retentionDays,setRetentionDays,setPreference,storageAvailable,hydrated}=useAppStore();const [filter,setFilter]=useState("all");const [editing,setEditing]=useState<string|null>(null);const {register,handleSubmit,reset,setValue,formState:{errors}}=useForm<FormValues>({resolver:zodResolver(schema),defaultValues:{regionCode:search.get("region")??"",note:"",startDate:"2026-07-13",endDate:"2026-07-13",consent:false}});
  useEffect(()=>{const code=search.get("region");if(code)setValue("regionCode",code);},[search,setValue]);
  const filtered=useMemo(()=>filter==="all"?visits:visits.filter((item)=>item.regionCode===filter),[filter,visits]);
  if(!hydrated)return <div aria-label="방문 저장소 준비 중" className="h-96 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800"/>;
  function submit(values:FormValues){const region=REGIONS.find((item)=>item.code===values.regionCode)!;saveVisit({id:editing??globalThis.crypto.randomUUID(),regionCode:region.code,regionName:region.name,note:values.note,startDate:values.startDate,endDate:values.endDate,consent:values.consent,createdAt:new Date().toISOString()});setEditing(null);reset({regionCode:"",note:"",startDate:values.startDate,endDate:values.endDate,consent:false});}
  function edit(id:string){const visit=visits.find((item)=>item.id===id);if(!visit)return;setEditing(id);reset({regionCode:visit.regionCode,note:visit.note,startDate:visit.startDate,endDate:visit.endDate,consent:visit.consent});window.scrollTo({top:0,behavior:"smooth"});}
  function exportJson(){downloadText("mokpo-watersafe-visits.json",JSON.stringify(visits,null,2));} function exportCsv(){const clean=(value:string)=>`"${value.replaceAll('"','""')}"`;downloadText("mokpo-watersafe-visits.csv",["순서,행정동,메모,시작일,종료일,시작시간,종료시간",...visits.map((v)=>[String(v.sequence??""),v.regionName,v.note,v.startDate,v.endDate,v.startTime??"",v.endTime??""].map(clean).join(","))].join("\n"),"text/csv;charset=utf-8");}
  return <><PageHeader title="방문 이력" description="행정동·날짜를 직접 등록하거나, 현재 시뮬레이션 날짜 기준 무작위 가상 이동 동선을 만들어 확진자 겹침 알림을 시험할 수 있습니다."/>{!storageAvailable&&<p role="alert" className="mb-4 rounded-xl bg-amber-100 p-3 text-sm font-bold text-amber-950">localStorage를 사용할 수 없어 새로고침 후 데이터가 유지되지 않을 수 있습니다.</p>}
    <div className="grid gap-5 xl:grid-cols-[380px_minmax(0,1fr)]"><Card className="self-start xl:sticky xl:top-20"><CardHeader><CardTitle>{editing?"방문 이력 수정":"방문 이력 등록"}</CardTitle></CardHeader><CardContent><form onSubmit={handleSubmit(submit)} className="space-y-4"><label className="block text-sm font-bold">방문 행정동<Select {...register("regionCode")} className="mt-1"><option value="">선택</option>{REGIONS.map((region)=><option key={region.code} value={region.code}>{region.name}</option>)}</Select>{errors.regionCode&&<span className="text-xs text-rose-600">{errors.regionCode.message}</span>}</label><label className="block text-sm font-bold">방문 장소 메모 (선택)<Textarea {...register("note")} placeholder="상세 주소 대신 간단한 메모" className="mt-1"/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-bold">시작일<Input type="date" {...register("startDate")} className="mt-1"/></label><label className="text-sm font-bold">종료일<Input type="date" {...register("endDate")} className="mt-1"/>{errors.endDate&&<span className="text-xs text-rose-600">{errors.endDate.message}</span>}</label></div><label className="flex items-start gap-2 text-sm"><input type="checkbox" {...register("consent")} className="mt-1"/><span>이 브라우저에 행정동·날짜·메모를 저장하는 데 동의합니다. 로그인 저장은 별도 동의 시에만 가능합니다.</span></label>{errors.consent&&<p className="text-xs text-rose-600">{errors.consent.message}</p>}<Button type="submit" className="w-full" disabled={!hydrated}><Plus className="size-4"/>{!hydrated?"저장소 준비 중":editing?"수정 저장":"방문 이력 저장"}</Button></form></CardContent></Card>
      <div className="space-y-5"><Card><CardContent className="flex flex-wrap gap-3 pt-5"><Button onClick={loadDemoRoute}><Route className="size-4"/>랜덤 가상 동선 만들기</Button><Select value={filter} onChange={(event)=>setFilter(event.target.value)} className="w-44"><option value="all">모든 행정동</option>{REGIONS.filter((region)=>visits.some((v)=>v.regionCode===region.code)).map((region)=><option key={region.code} value={region.code}>{region.name}</option>)}</Select><Button variant="outline" onClick={exportCsv}><Download className="size-4"/>CSV</Button><Button variant="outline" onClick={exportJson}><Download className="size-4"/>JSON</Button><label className="ml-auto flex items-center gap-2 text-sm">보관 기간<Select value={retentionDays} onChange={(event)=>setRetentionDays(Number(event.target.value))} className="w-28"><option value="30">30일</option><option value="90">90일</option><option value="365">1년</option></Select></label><Button variant="destructive" onClick={()=>{if(confirm("모든 방문 이력을 삭제할까요?"))clearVisits();}} disabled={!visits.length}>전체 삭제</Button></CardContent></Card>
      <section aria-label="방문 기록 목록" className="space-y-3">{filtered.length?filtered.map((visit)=>{const match=matches.find((item)=>item.visit.id===visit.id);return <Card key={visit.id}><CardContent className="pt-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">{visit.sequence&&<span className="mr-2 text-cyan-700">#{visit.sequence}</span>}{visit.regionName}{visit.isMock&&<span className="ml-2 rounded bg-violet-100 px-2 py-1 text-xs text-violet-800">가상 동선</span>}</h2><p className="text-sm text-slate-500">{visit.startDate}{visit.startTime&&visit.endTime?` ${visit.startTime}~${visit.endTime}`:` ~ ${visit.endDate}`}{visit.note&&` · ${visit.note}`}</p></div><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={()=>edit(visit.id)} aria-label="방문 이력 수정"><Pencil className="size-4"/></Button><Button variant="ghost" size="icon" onClick={()=>deleteVisit(visit.id)} aria-label="방문 이력 삭제"><Trash2 className="size-4"/></Button></div></div>{match&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-900 dark:bg-amber-950"><div className="flex items-center gap-2"><ShieldAlert className="size-5"/><RiskBadge level={match.severity}/></div><ul className="mt-2 space-y-1 text-sm">{match.messages.map((message)=><li key={message}>· {message}</li>)}</ul><p className="mt-3 text-xs font-bold">이 결과는 의료적 진단이 아닌 시연용 위험 비교입니다.</p><div className="mt-3 flex flex-wrap gap-2 text-sm font-bold"><Link href={`/regions/${visit.regionCode}`} className="rounded-lg border border-slate-300 px-3 py-2 dark:border-slate-700">지역 상세 보기</Link><Link href="/safety" className="rounded-lg border border-slate-300 px-3 py-2 dark:border-slate-700">안전수칙 보기</Link><Link href="/facilities" className="rounded-lg border border-slate-300 px-3 py-2 dark:border-slate-700">근처 병원 찾기</Link><button onClick={()=>setPreference("visit-alert",false)} className="rounded-lg border border-slate-300 px-3 py-2 dark:border-slate-700">알림 끄기</button><button onClick={()=>deleteVisit(visit.id)} className="rounded-lg bg-rose-700 px-3 py-2 text-white">방문 이력 삭제</button></div></div>}</CardContent></Card>}):<div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center dark:border-slate-700"><p className="font-bold">등록된 방문 이력이 없습니다.</p><p className="mt-1 text-sm text-slate-500">왼쪽 양식 또는 ‘가상 동선 만들기’로 추가하세요.</p></div>}</section></div></div>
  </>}
