"use client";
import { List, Map, MapPin, Navigation, Phone } from "lucide-react";
import { useMemo, useState } from "react";
import { PageHeader } from "@/components/common/page-header";
import { EmptyState } from "@/components/common/empty-state";
import { useAppStore } from "@/components/providers/app-store";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { MOCK_FACILITIES } from "@/data/facilities";
import { SCENARIOS } from "@/config/scenarios";

const labels={hospital:"병원",clinic:"의원",emergency:"응급실","health-center":"보건소"};
export function FacilityFinder(){const {scenarioId}=useAppStore();const scenario=SCENARIOS.find((item)=>item.id===scenarioId);const [type,setType]=useState("all");const [department,setDepartment]=useState("all");const [openOnly,setOpenOnly]=useState(false);const [view,setView]=useState<"list"|"map">("list");const [query,setQuery]=useState("");const [location,setLocation]=useState("");const [position,setPosition]=useState<{latitude:number;longitude:number}|null>(null);const facilities=useMemo(()=>(scenario?.flags?.noFacilities?[]:MOCK_FACILITIES).map((item)=>position?{...item,distanceKm:haversine(position.latitude,position.longitude,item.latitude,item.longitude)}:item).filter((item)=>(type==="all"||item.type===type)&&(department==="all"||item.departments.includes(department))&&(!openOnly||item.emergency||(new Date().getHours()>=9&&new Date().getHours()<18))&&(item.name.includes(query)||item.address.includes(query))).sort((a,b)=>a.distanceKm-b.distanceKm),[scenario,type,department,query,openOnly,position]);
  function locate(){if(!navigator.geolocation){setLocation("위치정보 미지원 · 행정동을 검색하세요.");return;}navigator.geolocation.getCurrentPosition((value)=>{setPosition({latitude:value.coords.latitude,longitude:value.coords.longitude});setLocation("현재 위치 기준 거리를 계산했습니다. 위치는 저장하지 않습니다.");},()=>setLocation("위치 권한이 거부되었습니다. 행정동 검색을 이용하세요."),{timeout:5000});}
  return <><PageHeader title="주변 의료기관 찾기" description="목포시 해커톤 테스트용 가상 기관 정보입니다. 운영시간·진료 가능 여부는 실제 방문에 사용할 수 없습니다." actions={<div className="flex gap-2"><Button variant={view==="list"?"default":"outline"} onClick={()=>setView("list")}><List className="size-4"/>목록</Button><Button variant={view==="map"?"default":"outline"} onClick={()=>setView("map")}><Map className="size-4"/>지도</Button></div>}/><div className="mb-5 rounded-xl border border-rose-300 bg-rose-50 p-4 text-sm dark:bg-rose-950"><strong>중요:</strong> 기관명·주소·전화번호·운영시간·진료과목은 모두 시연용 예시 정보입니다. 실제 방문이나 연락에 사용하지 마세요.</div><div className="mb-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-5 dark:border-slate-800 dark:bg-slate-900"><Input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="기관명 또는 행정동"/><Select value={type} onChange={(e)=>setType(e.target.value)}><option value="all">모든 기관 유형</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select><Select value={department} onChange={(e)=>setDepartment(e.target.value)}><option value="all">모든 진료과목</option><option>내과</option><option>소아청소년과</option><option>응급의학과</option><option>가정의학과</option></Select><label className="flex items-center gap-2 rounded-xl border border-slate-300 px-3 text-sm dark:border-slate-700"><input type="checkbox" checked={openOnly} onChange={(e)=>setOpenOnly(e.target.checked)}/>현재 운영 중 (예시)</label><Button variant="outline" onClick={locate}><Navigation className="size-4"/>현재 위치</Button></div>{location&&<p role="status" className="mb-4 text-sm">{location}</p>}
    {facilities.length===0?<EmptyState title="검색 결과가 없습니다" description="필터를 바꾸거나 다른 행정동을 검색해 보세요. 현재 시나리오가 빈 결과를 시연할 수도 있습니다."/>:view==="map"?<div className="relative min-h-[560px] overflow-hidden rounded-2xl border border-cyan-200 bg-[radial-gradient(circle,#cffafe,#e0f2fe_45%,#f8fafc)] dark:border-cyan-900 dark:bg-slate-900">{facilities.map((item,index)=><div key={item.id} className="absolute" style={{left:`${15+(index*19)%75}%`,top:`${20+(index*23)%65}%`}}><MapPin className="size-9 fill-cyan-700 text-white"/><span className="absolute left-1/2 top-full -translate-x-1/2 whitespace-nowrap rounded bg-white p-1 text-xs font-bold text-slate-900 shadow">{item.name}</span></div>)}<p className="absolute bottom-3 left-3 rounded bg-white/90 p-2 text-xs text-slate-900">위치는 시연용 예시 좌표입니다.</p></div>:<div className="grid gap-4 md:grid-cols-2">{facilities.map((item)=><Card key={item.id}><CardContent className="pt-5"><div className="flex justify-between"><div><span className="text-xs font-bold text-cyan-700">{labels[item.type]}</span><h2 className="text-xl font-black">{item.name}</h2></div><strong>{item.distanceKm.toFixed(1)}km</strong></div><dl className="mt-4 space-y-2 text-sm"><div><dt className="inline text-slate-500">주소 </dt><dd className="inline">{item.address}</dd></div><div><dt className="inline text-slate-500">과목 </dt><dd className="inline">{item.departments.join(", ")}</dd></div><div><dt className="inline text-slate-500">운영 </dt><dd className="inline">{item.hours}</dd></div><div><dt className="inline text-slate-500">응급실 </dt><dd className="inline">{item.emergency?"예 (시연)":"아니오"}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2"><a href={`tel:${item.phone}`} className="inline-flex items-center gap-1 rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold dark:border-slate-700"><Phone className="size-4"/>전화</a><a href={`https://map.kakao.com/link/to/${encodeURIComponent(item.name)},${item.latitude},${item.longitude}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold dark:border-slate-700"><Navigation className="size-4"/>길찾기</a><button onClick={()=>setView("map")} className="inline-flex items-center gap-1 px-3 py-2 text-sm font-bold text-cyan-700"><Map className="size-4"/>지도</button></div></CardContent></Card>)}</div>}</>}

function haversine(lat1:number,lng1:number,lat2:number,lng2:number){const toRad=(value:number)=>value*Math.PI/180;const dLat=toRad(lat2-lat1);const dLng=toRad(lng2-lng1);const value=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(value),Math.sqrt(1-value));}
