"use client";
import Link from "next/link";
import { Bell, Check, ExternalLink } from "lucide-react";
import { useState } from "react";
import { PageHeader } from "@/components/common/page-header";
import { EmptyState } from "@/components/common/empty-state";
import { RiskBadge } from "@/components/common/risk-badge";
import { useAppStore } from "@/components/providers/app-store";
import { notifyBrowserOfVisitMatches } from "@/services/browser-notifications";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { NotificationItem } from "@/types";

const labels:Record<NotificationItem["type"],string>={"risk-rise":"관심 지역 위험도 상승","visit-alert":"방문 동선·확진자 겹침","case-surge":"가상 확진 급증",water:"가상 수질 기준 초과","data-update":"데이터 갱신",resolved:"경보 해제",missing:"데이터 누락",stale:"오래된 데이터"};
export function NotificationCenter(){const {notifications,markRead,preferences,setPreference}=useAppStore();const [permission,setPermission]=useState(typeof Notification==="undefined"?"unsupported":Notification.permission);async function request(){if(typeof Notification==="undefined"){setPermission("unsupported");return;}const value=await Notification.requestPermission();setPermission(value);if(value==="granted")await notifyBrowserOfVisitMatches(notifications);}
  return <><PageHeader title="알림" description="관심 지역과 방문 지역의 가상 위험 변화를 확인합니다. 브라우저 알림은 명시적으로 허용한 경우에만 켜집니다." actions={<Button variant="outline" onClick={request}><Bell className="size-4"/>브라우저 알림 {permission==="granted"?"허용됨":"허용하기"}</Button>}/><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><section className="space-y-3">{notifications.length?notifications.map((item)=><Card key={item.id} className={item.read?"opacity-70":"border-cyan-300 dark:border-cyan-800"}><CardContent className="pt-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-cyan-700">{labels[item.type]} · 가상 데이터</p><h2 className="mt-1 text-lg font-black">{item.title}</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">{item.description}</p><p className="mt-2 text-xs text-slate-500">{item.createdAt}</p></div><RiskBadge level={item.level}/></div><div className="mt-4 flex gap-2"><Link href={item.href} className="inline-flex items-center gap-1 font-bold text-cyan-700">관련 페이지 <ExternalLink className="size-4"/></Link>{!item.read&&<button onClick={()=>markRead(item.id)} className="ml-auto inline-flex items-center gap-1 text-sm font-bold"><Check className="size-4"/>읽음</button>}</div></CardContent></Card>):<EmptyState title="표시할 가상 알림이 없습니다" description="지도에서 관심 지역을 추가하거나 방문 이력을 등록하세요."/>}</section><Card className="self-start xl:sticky xl:top-20"><CardHeader><CardTitle>알림 종류 설정</CardTitle></CardHeader><CardContent className="space-y-2">{Object.entries(labels).map(([key,label])=><label key={key} className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 p-3 text-sm dark:border-slate-800"><span>{label}</span><input type="checkbox" checked={preferences[key as NotificationItem["type"]]} onChange={(event)=>setPreference(key as NotificationItem["type"],event.target.checked)} aria-label={`${label} 알림`}/></label>)}<p className="pt-3 text-xs text-slate-500">브라우저 권한을 거부해도 앱 안 알림 목록은 사용할 수 있습니다.</p></CardContent></Card></div></>}
