"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import { format, parseISO, subDays } from "date-fns";
import { ko } from "date-fns/locale";
import { AlertTriangle, ArrowRight, Droplets, Hospital, MapPin, ShieldCheck, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { useAppStore } from "@/components/providers/app-store";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { RiskBadge } from "@/components/common/risk-badge";
import { PageHeader } from "@/components/common/page-header";
import { summarizeRisk, getRiskRecords } from "@/services/risk-service";
import { HEALTHCARE_FACILITIES } from "@/data/facilities";

const MapPreview = dynamic(() => import("@/components/map/kakao-map").then((module) => module.KakaoMap), { ssr: false, loading: () => <div className="h-[360px] animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800" /> });
const TrendChart = dynamic(() => import("./trend-chart").then((module) => module.TrendChart), { ssr: false, loading: () => <div className="h-64 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800" /> });

export function Dashboard() {
  const { records, scenarioId, date, seed, simulationSettings, visits, matches, notifications } = useAppStore(); const summary = summarizeRisk(records); const [nearby, setNearby] = useState("현재 위치를 사용하지 않았습니다.");
  const trend = useMemo(() => Array.from({ length: 7 }, (_, index) => { const day = format(subDays(parseISO(date), 6-index), "yyyy-MM-dd"); const values = summarizeRisk(getRiskRecords(scenarioId, day, { ...simulationSettings, seed })); return { date: format(parseISO(day), "M/d"), cases: values.confirmed, anomalies: values.waterAnomalies }; }), [scenarioId,date,seed,simulationSettings]);
  function locate() { if (!navigator.geolocation) { setNearby("이 브라우저는 위치정보를 지원하지 않습니다. 행정동 검색을 이용해 주세요."); return; } navigator.geolocation.getCurrentPosition((position) => { const nearest=[...records].sort((a,b)=>distance(position.coords.latitude,position.coords.longitude,a.latitude,a.longitude)-distance(position.coords.latitude,position.coords.longitude,b.latitude,b.longitude))[0]; setNearby(`현재 위치 기준 가장 가까운 행정동 중심은 ${nearest?.regionName ?? "상동"}이며, 위치는 저장하지 않습니다.`); }, () => setNearby("위치 권한이 거부되었습니다. 위험 지도에서 행정동을 직접 검색해 주세요."), { timeout: 5000 }); }
  const cards = [{ label:"최근 7일 가상 확진", value:trend.reduce((sum,item)=>sum+item.cases,0), icon:Users, note:"7일간 행정동 집계 합계" },{ label:"최근 7일 가상 수질 이상", value:trend.reduce((sum,item)=>sum+item.anomalies,0), icon:Droplets, note:"7일간 이상 지역 건수" },{ label:"주의·경계 지역", value:summary.counts.caution+summary.counts.warning, icon:AlertTriangle, note:"선택일 주의 이상 가상 단계" }];
  return <><PageHeader title="목포시 가상 위험 현황" description={`${format(parseISO(date), "yyyy년 M월 d일", { locale: ko })} 기준 · 선택한 시나리오에 따라 모든 수치가 함께 바뀝니다.`} actions={<Link href="/map" className="inline-flex items-center gap-2 rounded-xl bg-cyan-700 px-5 py-3 font-bold text-white">전체 지도 <ArrowRight className="size-4"/></Link>} />
    <section className="grid gap-4 sm:grid-cols-3" aria-label="위험 현황 요약">{cards.map(({label,value,icon:Icon,note})=><Card key={label}><CardContent className="flex items-center gap-4 pt-5"><span className="grid size-12 place-items-center rounded-2xl bg-cyan-100 text-cyan-800 dark:bg-cyan-950 dark:text-cyan-200"><Icon/></span><div><p className="text-sm text-slate-600 dark:text-slate-400">{label}</p><p className="text-3xl font-black">{value}</p><p className="text-xs text-slate-500">{note}</p></div></CardContent></Card>)}</section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><Card><CardHeader><CardTitle>최근 7일 가상 위험 추세</CardTitle><CardDescription>가상 확진 집계와 가상 수질 이상 건수</CardDescription></CardHeader><CardContent><TrendChart data={trend}/></CardContent></Card><Card><CardHeader><CardTitle>단계별 행정동</CardTitle><CardDescription>색상·문자·패턴을 함께 표시합니다.</CardDescription></CardHeader><CardContent className="space-y-3">{Object.entries(summary.counts).map(([level,count])=><div key={level} className="flex items-center justify-between"><RiskBadge level={level as keyof typeof summary.counts}/><strong>{count}곳</strong></div>)}<div className="mt-4 rounded-xl bg-rose-50 p-4 dark:bg-rose-950"><p className="text-sm font-bold">가장 높은 가상 위험 점수</p><div className="mt-2 flex items-center justify-between"><Link href={`/regions/${summary.highest.regionCode}`} className="font-black underline">{summary.highest.regionName}</Link><RiskBadge level={summary.highest.riskLevel} score={summary.highest.riskScore}/></div></div></CardContent></Card></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Card><CardHeader><CardTitle>목포시 지도 미리보기</CardTitle><CardDescription>위험은 특정 시설이 아닌 행정동 단위로만 표시됩니다.</CardDescription></CardHeader><CardContent><MapPreview records={records} className="min-h-[360px]"/></CardContent></Card><div className="space-y-4"><Card><CardHeader><CardTitle>현재 위치 주변</CardTitle></CardHeader><CardContent><p className="text-sm text-slate-600 dark:text-slate-400">{nearby}</p><button onClick={locate} className="mt-3 inline-flex items-center gap-2 font-bold text-cyan-700"><MapPin className="size-4"/>현재 위치 확인</button></CardContent></Card><Card><CardHeader><CardTitle>최근 방문 비교</CardTitle></CardHeader><CardContent>{visits.length ? <><p className="font-bold">{visits[0].regionName} · {visits[0].startDate}</p><p className="mt-2 text-sm">{matches[0]?.messages[0] ?? "현재 생성된 가상 위험과 일치하지 않습니다."}</p></> : <p className="text-sm text-slate-600 dark:text-slate-400">등록된 방문 이력이 없습니다.</p>}<Link href="/visits" className="mt-3 inline-block font-bold text-cyan-700">방문 이력 관리 →</Link></CardContent></Card></div></section>
    <section className="mt-4 grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle>최근 가상 경보</CardTitle></CardHeader><CardContent>{notifications[0]?.title ?? (records.find((item)=>item.riskLevel==="warning"||item.riskLevel==="caution") ? `${records.find((item)=>item.riskLevel==="warning"||item.riskLevel==="caution")?.regionName} 가상 위험 경보` : "현재 생성된 가상 주의 이상 경보가 없습니다.")}</CardContent></Card><Card><CardHeader><CardTitle>주요 의료기관</CardTitle></CardHeader><CardContent><p className="font-bold">{HEALTHCARE_FACILITIES[0].name}</p><p className="text-sm text-slate-500">목포시 공식 병원현황 기반 · 방문 전 운영 확인</p><Link href="/facilities" className="mt-3 inline-flex items-center gap-2 font-bold text-cyan-700"><Hospital className="size-4"/>기관 찾기</Link></CardContent></Card><Card><CardHeader><CardTitle>안전수칙</CardTitle></CardHeader><CardContent><p className="text-sm">안전한 물과 음식, 손 위생에 관한 일반 예방수칙을 확인하세요.</p><Link href="/safety" className="mt-3 inline-flex items-center gap-2 font-bold text-cyan-700"><ShieldCheck className="size-4"/>안전수칙 보기</Link></CardContent></Card></section>
  </>;
}

function distance(lat1:number,lng1:number,lat2:number,lng2:number){const toRad=(value:number)=>value*Math.PI/180;const dLat=toRad(lat2-lat1);const dLng=toRad(lng2-lng1);const value=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(value),Math.sqrt(1-value));}
