"use client";
import { LogIn, UserPlus } from "lucide-react";
import { useState } from "react";
import { z } from "zod";
import { PageHeader } from "@/components/common/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
const schema=z.object({email:z.email("올바른 이메일을 입력하세요."),password:z.string().min(8,"비밀번호는 8자 이상이어야 합니다.")});
export function AuthForm(){const [mode,setMode]=useState<"login"|"signup">("login");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function submit(event:React.FormEvent){event.preventDefault();const parsed=schema.safeParse({email,password});if(!parsed.success){setMessage(parsed.error.issues[0]?.message??"입력을 확인하세요.");return;}const supabase=createSupabaseBrowserClient();if(!supabase){setMessage("Supabase 환경변수가 없어 게스트 데모 모드로 실행 중입니다. 방문 기록은 이 브라우저에만 저장됩니다.");return;}setBusy(true);const result=mode==="login"?await supabase.auth.signInWithPassword(parsed.data):await supabase.auth.signUp(parsed.data);setBusy(false);setMessage(result.error?result.error.message:mode==="login"?"로그인되었습니다.":"가입 확인 이메일을 확인하세요.");}
  return <><PageHeader title="로그인·회원가입" description="로그인 사용자의 방문 이력도 명시적으로 동의한 경우에만 Supabase에 저장합니다. 게스트는 브라우저 로컬 저장만 사용합니다."/><Card className="mx-auto max-w-md"><CardHeader><CardTitle>{mode==="login"?"로그인":"회원가입"}</CardTitle></CardHeader><CardContent><div className="mb-5 grid grid-cols-2 gap-2"><Button variant={mode==="login"?"default":"outline"} onClick={()=>setMode("login")}><LogIn className="size-4"/>로그인</Button><Button variant={mode==="signup"?"default":"outline"} onClick={()=>setMode("signup")}><UserPlus className="size-4"/>회원가입</Button></div><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-bold">이메일<Input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} autoComplete="email" className="mt-1"/></label><label className="block text-sm font-bold">비밀번호<Input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete={mode==="login"?"current-password":"new-password"} className="mt-1"/></label><Button type="submit" className="w-full" disabled={busy}>{busy?"처리 중...":mode==="login"?"로그인":"계정 만들기"}</Button></form>{message&&<p role="status" className="mt-4 rounded-xl bg-slate-100 p-3 text-sm dark:bg-slate-800">{message}</p>}<p className="mt-5 text-xs text-slate-500">서비스는 이름, 성별, 나이, 전화번호, 상세주소, GPS 이동경로를 수집하지 않습니다.</p></CardContent></Card></>}
